Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.provision "shell", path: "provision.sh"

  config.vm.synced_folder "../dev_ws/", "/home/vagrant/dev_ws"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.ssh.extra_args = ["-t", "cd dev_ws; bash --login"]
end
